name: variables-secret workflow

on: workflow_dispatch

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    - name: Login to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${{ env.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name: Push Docker Image to Docker Hub
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    # only run the deply job if it is pushed to main branch
    if : github.ref == 'refs/heads/main'
    needs: docker
    concurrency:
      group: prod-deploy
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Docker Run
      timeout-minutes: 1
      run: |
       echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
       sleep 600