name : variables-secret workflow

on : push

env: 
 CONTAINER_REGISTRY : docker.io
 DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
 IMAGE_NAME : github-actions-nginx

jobs:
  docker : 
    runs-on: ubuntu-latest
    steps:
    - name : checkout code
      uses : actions/checkout@v4  

    - name : Build Docker Image 
      run : echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 
    
    - name : Login to Docker Hub
      env : 
        DOCKER_PASSWORD: dckr_pat_cU8NgmY5VLriQns2GTaJeAMisl4
        
      run : echo ${{ env.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name : Push Docker Image to Docker Hub
      run : echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy : 
    needs : docker
    runs-on: ubuntu-latest
    steps: 
    - name : checkout code
      uses : actions/checkout@v4

    - name : Docket Run
      run : echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest